#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width 0
bspc config window_gap 15
bsp config presel_feedback_color "#ffffff"
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config top_padding 20

bspc config focused_border_color "#545862"
bspc config normal_border_color "#353b45"

bspc config gapless_monocle false

$HOME/.config/polybar/launch.sh
